apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ include "version-monitor.fullname" . }}
data:
  CONFIG: "/config/config.yaml"
  LISTEN: ":8080"
  VERBOSE: {{ .Values.verbose | toString | quote }}
